### PR TITLE
WIP chore: drop twing for twig-lexer

### LINKED ISSUE #4: Keep the whitespace modifier in `{%-`, `{{-` and `{#-`
See https://github.com/ericmorand/twing/pull/321 and https://github.com/ericmorand/twing/pull/326.

Actually there is no way to keep the whitespace modifier in `{%-`, `{{-` and `{#-`.
They respectively _converted_ to `{%`, `{{` and `{#`, and the same behaviour happens for the closing tags.

An other thing, the following code
```twig
hello
{{- world }}
```

is prettified to
```twig
hello{{ world }}
```

because `hello\n` is trimmed at the end by the Twing lexer, see https://github.com/ericmorand/twing/issues/321#issuecomment-476987422.

### LINKED ISSUE #13: Standalone support: package Twing
In #11, I encountered a tons of problem when trying to package Twing into the standalone build.
Problems about node globals/builtins, crypto things, ...... 
I've tried to tweak Rollup, nope. I've even tried to use webpack, but the standalone build was legit about ~4 MB... Maybe I should give a try to Parcel... 

But this should be definitly fixed. 
I don't like to tell the user he should import Twing himself...  
```html
<script src="https://unpkg.com/prettier/standalone.js"></script>
<script src="https://cdn.jsdelivr.net/npm/twing/dist/lib.min.js"></script>
<script src="https://unpkg.com/@kocal/prettier-plugin-twig/standalone.js"></script>
```

### LINKED ISSUE #15: Use a new Twig parser
[Twing](https://github.com/ericmorand/twing) is really nice and works well, but there is too much issues: 
  - whitespace control modifier are not preserved: #4, https://github.com/ericmorand/twing/issues/321, https://github.com/ericmorand/twing/pull/326
  - unknown filters thrown an error (`{{ foo | bar }}`):
Sélection_508
  - macros/blocks/traits (#14) are handled differenlty (with references) 

IMO, I think the best solution is to use a new parser that will be especially written for this plugin, a parser which takes code, lex it, parse it, and returns AST.

### PR DESCRIPTION
**Pull request by Kocal**
@ericmorand have created the perfect package to lex Twig code: [twig-lexer](https://github.com/NightlyCommit/twig-lexer)

When using Twing, we had some issues about whitespace control modifier (`{%-`, `{{-`, ...) because they were simply removed from tokens and nodes (see ericmorand/twing/issues/321 and ericmorand/twing/pull/326).

But with twig-lexer everything is preserved as tokens, [example](https://runkit.com/embed/ihe7sangdhvs):
Sélection_916
And so it means that we will be able to print those modifiers back :)

~Actually I will have to rewrite everything since we will use tokens instead of nodes to prettify Twig code.~ In fact not everything, but we have to make sure we are using an AST and not only tokens (even with a token stream), otherwise it will be a pain in the ass.
Since we won't directly use tokens for an AST, we need to find a way to reserve whitespace control modifiers. That can be weird, but I think we can store (on certain types of node) the opening/closing tags with whitespace modifier controls. 🤔

And also use FastPath instead of our own print function because of (https://github.com/prettier/plugin-php/issues/12):
- comment handling around every single node
- access to the parents all the way to the root
- It also allows the multiparser feature to exist 

This PR will close #15, close #4 and close #13

### CODE REVIEW

**Comment by ericmorand** [comment]
Glad to see that this will help you. It will be the lexer used by the next major version of Twing.

Just a remark about the "WHITESPACE" tokens. They may seem redundant - after all they can easily be resolved by simple comparison of value and line/column properties of the tokens - but I felt they would make life easier for tools like yours - less code from your side is always better.

The drawback is that they have to be ignored by eventual parsers (like Twing parser) but this is trivial.

Another remark : I see that you implemented a token stream which is very good. I have been torned between having one included in twig-lexer or not. Actually, Twing will also need one so maybe it could be beneficial to have it included in twig-lexer and tested there instead of having it spread in multiple projects. It would come as a separate module that export a constructor that takes an array of tokens as parameter. With tree shaking, it would add zero to consumer packaged if not used.

**Comment by Kocal** [comment]
Don't worry for the `WHITESPACE` tokens, in fact I think I will skip everyone of them since it's Prettier that will decide how to render whitespaces (see https://github.com/Kocal/prettier-plugin-twig/blob/master/src/printer.js#L59 and https://github.com/prettier/prettier/blob/master/commands.md#line).

For the token stream, it would be really nice since the one _I wrote_ is like 80% copy/pasted from Twing. :sweat_smile:

**Comment by ericmorand** [comment]
It's a deal. I'll add it to twig-lexer. And loot your test suite if you don't mind.

**Comment by Kocal** [comment]
Yeah go for it! :)

**Comment by ericmorand** [comment]
@Kocal there is some breaking changes in twig-lexer@0.5. Namely, the getters are now using the native syntax - fro exemplae `Token::getValue` has been replaced by `Token::value`. I want to take the opportunity to have the best code possible while we are still below 1.0 - but 1.0 should be there in no time, I feel like the API is quite complete now.

Also the token stream is now included in the library. Thanks for your work on it.

**Comment by Kocal** [comment]
Thanks for the info @ericmorand, I will try it when I will have some time :)

**Pull request closed without merging**
